apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mobile-game-template.fullname" . }}
  labels:
    {{- include "mobile-game-template.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "mobile-game-template.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mobile-game-template.labels" . | nindent 8 }}
    spec:
      containers:
        - name: backend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          env:
            - name: LOG_LEVEL
              value: {{ .Values.config.logLevel | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
