apiVersion: v1
kind: Service
metadata:
  name: {{ include "mobile-game-template.fullname" . }}
  labels:
    {{- include "mobile-game-template.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    {{- include "mobile-game-template.labels" . | nindent 4 }}
