// AUTO-GENERATED by scripts/generate-nav.mjs from docs/mkdocs.yml — do not edit by hand.
export interface NavLeaf {
  title: string;
  kind: "md";
  path: string;
  source: string;
}
export interface NavExternal {
  title: string;
  kind: "external";
  href: string;
}
export interface NavSection {
  title: string;
  kind: "section";
  children: NavNode[];
}
export type NavNode = NavLeaf | NavExternal | NavSection;

export const navTree: NavNode[] = [
  {
    "title": "Home",
    "kind": "md",
    "path": "/docs",
    "source": "docs/index.md"
  },
  {
    "title": "Architecture",
    "kind": "md",
    "path": "/ARCHITECTURE",
    "source": "docs/ARCHITECTURE.md"
  },
  {
    "title": "Development",
    "kind": "md",
    "path": "/DEVELOPMENT",
    "source": "docs/DEVELOPMENT.md"
  },
  {
    "title": "Testing",
    "kind": "md",
    "path": "/TESTING",
    "source": "docs/TESTING.md"
  },
  {
    "title": "Glossary",
    "kind": "md",
    "path": "/GLOSSARY",
    "source": "docs/GLOSSARY.md"
  },
  {
    "title": "Troubleshooting",
    "kind": "md",
    "path": "/TROUBLESHOOTING",
    "source": "docs/TROUBLESHOOTING.md"
  },
  {
    "title": "Dependency Policy",
    "kind": "md",
    "path": "/DEPENDENCY_POLICY",
    "source": "docs/DEPENDENCY_POLICY.md"
  },
  {
    "title": "Documentation Standards",
    "kind": "md",
    "path": "/DOCUMENTATION_STANDARDS",
    "source": "docs/DOCUMENTATION_STANDARDS.md"
  },
  {
    "title": "Benchmarks",
    "kind": "md",
    "path": "/BENCHMARKS",
    "source": "docs/BENCHMARKS.md"
  },
  {
    "title": "Architecture Decisions",
    "kind": "section",
    "children": [
      {
        "title": "0001 Record Architecture Decisions",
        "kind": "md",
        "path": "/adr/0001-record-architecture-decisions",
        "source": "docs/adr/0001-record-architecture-decisions.md"
      },
      {
        "title": "0002 Rendering Approach",
        "kind": "md",
        "path": "/adr/0002-rendering-approach",
        "source": "docs/adr/0002-rendering-approach.md"
      },
      {
        "title": "0003 iOS Rendering Approach",
        "kind": "md",
        "path": "/adr/0003-ios-rendering-approach",
        "source": "docs/adr/0003-ios-rendering-approach.md"
      }
    ]
  },
  {
    "title": "Roadmap",
    "kind": "section",
    "children": [
      {
        "title": "Overview",
        "kind": "md",
        "path": "/moon/ROADMAP",
        "source": "docs/moon/ROADMAP.md"
      },
      {
        "title": "Changelog",
        "kind": "md",
        "path": "/moon/CHANGELOG",
        "source": "docs/moon/CHANGELOG.md"
      },
      {
        "title": "Gameplay",
        "kind": "md",
        "path": "/moon/roadmaps/gameplay",
        "source": "docs/moon/roadmaps/gameplay.md"
      },
      {
        "title": "UI/UX",
        "kind": "md",
        "path": "/moon/roadmaps/ui_ux",
        "source": "docs/moon/roadmaps/ui_ux.md"
      },
      {
        "title": "Performance",
        "kind": "md",
        "path": "/moon/roadmaps/performance",
        "source": "docs/moon/roadmaps/performance.md"
      },
      {
        "title": "Monetization",
        "kind": "md",
        "path": "/moon/roadmaps/monetization",
        "source": "docs/moon/roadmaps/monetization.md"
      },
      {
        "title": "Backend",
        "kind": "md",
        "path": "/moon/roadmaps/backend",
        "source": "docs/moon/roadmaps/backend.md"
      },
      {
        "title": "AI Systems",
        "kind": "md",
        "path": "/moon/roadmaps/ai_systems",
        "source": "docs/moon/roadmaps/ai_systems.md"
      },
      {
        "title": "QA & Testing",
        "kind": "md",
        "path": "/moon/roadmaps/qa_testing",
        "source": "docs/moon/roadmaps/qa_testing.md"
      },
      {
        "title": "iOS",
        "kind": "md",
        "path": "/moon/roadmaps/ios",
        "source": "docs/moon/roadmaps/ios.md"
      },
      {
        "title": "Shared Core",
        "kind": "md",
        "path": "/moon/roadmaps/shared_core",
        "source": "docs/moon/roadmaps/shared_core.md"
      }
    ]
  },
  {
    "title": "Design",
    "kind": "section",
    "children": [
      {
        "title": "Game Design Document",
        "kind": "md",
        "path": "/design/game_design_document",
        "source": "docs/design/game_design_document.md"
      },
      {
        "title": "Art Bible",
        "kind": "md",
        "path": "/design/art_bible",
        "source": "docs/design/art_bible.md"
      },
      {
        "title": "Audio Design",
        "kind": "md",
        "path": "/design/audio_design_document",
        "source": "docs/design/audio_design_document.md"
      },
      {
        "title": "Pitch Deck",
        "kind": "md",
        "path": "/design/pitch_deck",
        "source": "docs/design/pitch_deck.md"
      },
      {
        "title": "Production Roadmap",
        "kind": "md",
        "path": "/design/production_roadmap",
        "source": "docs/design/production_roadmap.md"
      },
      {
        "title": "QA Test Plan",
        "kind": "md",
        "path": "/design/qa_test_plan",
        "source": "docs/design/qa_test_plan.md"
      },
      {
        "title": "Technical Design Document",
        "kind": "md",
        "path": "/design/technical_design_document",
        "source": "docs/design/technical_design_document.md"
      }
    ]
  },
  {
    "title": "Research",
    "kind": "section",
    "children": [
      {
        "title": "Tower Defense Market",
        "kind": "md",
        "path": "/moon/reports/Tower Defense Market Research",
        "source": "docs/moon/reports/Tower Defense Market Research.md"
      },
      {
        "title": "Multiplayer Architecture",
        "kind": "md",
        "path": "/moon/research/Multiplayer Tower Defense Implementation",
        "source": "docs/moon/research/Multiplayer Tower Defense Implementation.md"
      }
    ]
  },
  {
    "title": "Codebase Guides",
    "kind": "section",
    "children": [
      {
        "title": "Repository Guide",
        "kind": "md",
        "path": "/repo/README",
        "source": "README.md"
      },
      {
        "title": "Contributing",
        "kind": "md",
        "path": "/repo/git/CONTRIBUTING",
        "source": "git/CONTRIBUTING.md"
      },
      {
        "title": "Shared Core",
        "kind": "md",
        "path": "/repo/core/README",
        "source": "core/README.md"
      },
      {
        "title": "Game State Machine",
        "kind": "md",
        "path": "/repo/core/src/game-state-machine",
        "source": "core/src/game-state-machine.md"
      },
      {
        "title": "iOS Font Assets",
        "kind": "md",
        "path": "/repo/ios/MyGame/Resources/Fonts/README",
        "source": "ios/MyGame/Resources/Fonts/README.md"
      },
      {
        "title": "Development Container",
        "kind": "md",
        "path": "/repo/-devcontainer/README",
        "source": ".devcontainer/README.md"
      }
    ]
  },
  {
    "title": "Infrastructure",
    "kind": "section",
    "children": [
      {
        "title": "Docker",
        "kind": "md",
        "path": "/repo/infra/global/docker/README",
        "source": "infra/global/docker/README.md"
      },
      {
        "title": "Kubernetes",
        "kind": "md",
        "path": "/repo/infra/global/k8s/README",
        "source": "infra/global/k8s/README.md"
      },
      {
        "title": "Helm",
        "kind": "md",
        "path": "/repo/infra/global/helm/README",
        "source": "infra/global/helm/README.md"
      },
      {
        "title": "Terraform",
        "kind": "md",
        "path": "/repo/infra/global/terraform/README",
        "source": "infra/global/terraform/README.md"
      },
      {
        "title": "Ansible",
        "kind": "md",
        "path": "/repo/infra/global/ansible/README",
        "source": "infra/global/ansible/README.md"
      }
    ]
  }
];

export const searchIndex: { title: string; path: string; source: string }[] = [
  {
    "title": "Home",
    "path": "/docs",
    "source": "docs/index.md"
  },
  {
    "title": "Architecture",
    "path": "/ARCHITECTURE",
    "source": "docs/ARCHITECTURE.md"
  },
  {
    "title": "Development",
    "path": "/DEVELOPMENT",
    "source": "docs/DEVELOPMENT.md"
  },
  {
    "title": "Testing",
    "path": "/TESTING",
    "source": "docs/TESTING.md"
  },
  {
    "title": "Glossary",
    "path": "/GLOSSARY",
    "source": "docs/GLOSSARY.md"
  },
  {
    "title": "Troubleshooting",
    "path": "/TROUBLESHOOTING",
    "source": "docs/TROUBLESHOOTING.md"
  },
  {
    "title": "Dependency Policy",
    "path": "/DEPENDENCY_POLICY",
    "source": "docs/DEPENDENCY_POLICY.md"
  },
  {
    "title": "Documentation Standards",
    "path": "/DOCUMENTATION_STANDARDS",
    "source": "docs/DOCUMENTATION_STANDARDS.md"
  },
  {
    "title": "Benchmarks",
    "path": "/BENCHMARKS",
    "source": "docs/BENCHMARKS.md"
  },
  {
    "title": "0001 Record Architecture Decisions",
    "path": "/adr/0001-record-architecture-decisions",
    "source": "docs/adr/0001-record-architecture-decisions.md"
  },
  {
    "title": "0002 Rendering Approach",
    "path": "/adr/0002-rendering-approach",
    "source": "docs/adr/0002-rendering-approach.md"
  },
  {
    "title": "0003 iOS Rendering Approach",
    "path": "/adr/0003-ios-rendering-approach",
    "source": "docs/adr/0003-ios-rendering-approach.md"
  },
  {
    "title": "Overview",
    "path": "/moon/ROADMAP",
    "source": "docs/moon/ROADMAP.md"
  },
  {
    "title": "Changelog",
    "path": "/moon/CHANGELOG",
    "source": "docs/moon/CHANGELOG.md"
  },
  {
    "title": "Gameplay",
    "path": "/moon/roadmaps/gameplay",
    "source": "docs/moon/roadmaps/gameplay.md"
  },
  {
    "title": "UI/UX",
    "path": "/moon/roadmaps/ui_ux",
    "source": "docs/moon/roadmaps/ui_ux.md"
  },
  {
    "title": "Performance",
    "path": "/moon/roadmaps/performance",
    "source": "docs/moon/roadmaps/performance.md"
  },
  {
    "title": "Monetization",
    "path": "/moon/roadmaps/monetization",
    "source": "docs/moon/roadmaps/monetization.md"
  },
  {
    "title": "Backend",
    "path": "/moon/roadmaps/backend",
    "source": "docs/moon/roadmaps/backend.md"
  },
  {
    "title": "AI Systems",
    "path": "/moon/roadmaps/ai_systems",
    "source": "docs/moon/roadmaps/ai_systems.md"
  },
  {
    "title": "QA & Testing",
    "path": "/moon/roadmaps/qa_testing",
    "source": "docs/moon/roadmaps/qa_testing.md"
  },
  {
    "title": "iOS",
    "path": "/moon/roadmaps/ios",
    "source": "docs/moon/roadmaps/ios.md"
  },
  {
    "title": "Shared Core",
    "path": "/moon/roadmaps/shared_core",
    "source": "docs/moon/roadmaps/shared_core.md"
  },
  {
    "title": "Game Design Document",
    "path": "/design/game_design_document",
    "source": "docs/design/game_design_document.md"
  },
  {
    "title": "Art Bible",
    "path": "/design/art_bible",
    "source": "docs/design/art_bible.md"
  },
  {
    "title": "Audio Design",
    "path": "/design/audio_design_document",
    "source": "docs/design/audio_design_document.md"
  },
  {
    "title": "Pitch Deck",
    "path": "/design/pitch_deck",
    "source": "docs/design/pitch_deck.md"
  },
  {
    "title": "Production Roadmap",
    "path": "/design/production_roadmap",
    "source": "docs/design/production_roadmap.md"
  },
  {
    "title": "QA Test Plan",
    "path": "/design/qa_test_plan",
    "source": "docs/design/qa_test_plan.md"
  },
  {
    "title": "Technical Design Document",
    "path": "/design/technical_design_document",
    "source": "docs/design/technical_design_document.md"
  },
  {
    "title": "Tower Defense Market",
    "path": "/moon/reports/Tower Defense Market Research",
    "source": "docs/moon/reports/Tower Defense Market Research.md"
  },
  {
    "title": "Multiplayer Architecture",
    "path": "/moon/research/Multiplayer Tower Defense Implementation",
    "source": "docs/moon/research/Multiplayer Tower Defense Implementation.md"
  },
  {
    "title": "Repository Guide",
    "path": "/repo/README",
    "source": "README.md"
  },
  {
    "title": "Contributing",
    "path": "/repo/git/CONTRIBUTING",
    "source": "git/CONTRIBUTING.md"
  },
  {
    "title": "Shared Core",
    "path": "/repo/core/README",
    "source": "core/README.md"
  },
  {
    "title": "Game State Machine",
    "path": "/repo/core/src/game-state-machine",
    "source": "core/src/game-state-machine.md"
  },
  {
    "title": "iOS Font Assets",
    "path": "/repo/ios/MyGame/Resources/Fonts/README",
    "source": "ios/MyGame/Resources/Fonts/README.md"
  },
  {
    "title": "Development Container",
    "path": "/repo/-devcontainer/README",
    "source": ".devcontainer/README.md"
  },
  {
    "title": "Docker",
    "path": "/repo/infra/global/docker/README",
    "source": "infra/global/docker/README.md"
  },
  {
    "title": "Kubernetes",
    "path": "/repo/infra/global/k8s/README",
    "source": "infra/global/k8s/README.md"
  },
  {
    "title": "Helm",
    "path": "/repo/infra/global/helm/README",
    "source": "infra/global/helm/README.md"
  },
  {
    "title": "Terraform",
    "path": "/repo/infra/global/terraform/README",
    "source": "infra/global/terraform/README.md"
  },
  {
    "title": "Ansible",
    "path": "/repo/infra/global/ansible/README",
    "source": "infra/global/ansible/README.md"
  }
];
